Passtival/passtival-client

.gitignore, README.md, eslint.config.js, index.html, package.json, pnpm-lock.yaml, src/App.tsx, src/main.tsx, src/vite-env.d.ts, tsconfig.app.json, tsconfig.json, tsconfig.node.json, vite.config.ts
- #1 
React 프로젝트를 설치한 상태이며, 추후 폴더 구조는 승택님과 함께 논의 후 설계할 예정입니다.
저희는 Git Flow 전략을 따릅니다.
main 브랜치는 배포용 브랜치로 사용하며
develop 브랜치는 배포 전 통합 개발 브랜치입니다.
기능 개발 시에는 항상 develop 브랜치에서 분기하여 브랜치를 생성합니다.
개발이 어느 정도 완료되면 develop 브랜치의 내용을 main으로 병합하여 배포를 진행할 예정입니다.
기능 개발을 시작하기 전, 먼저 develop 브랜치로 이동한 뒤 최신 상태를 반영합니다.
이를 위해 git fetch로 원격 정보를 가져오고, git pull로 실제 브랜치 내용을 업데이트합니다.
이후 GitHub 이슈 페이지에서 해당 이슈에 대응하는 새로운 브랜치를 생성하여 작업을 시작합니다.
요약 : develop 브랜치로 이동, git fetch 한번 하고 git pull 한번 한 후 issue 페이지에서 새로 만든 브랜치 이동
=> Init: 프로젝트 초기 세팅

src/App.tsx, src/main.tsx
📌 Summary
- #4 
📚 Tasks
기존에 실수로 react 설치 과정에서 제거하지 않은 파일을 발견하여 제거하였습니다..
=> [Fix] React 초기세팅 파일 제거

src/App.tsx, src/main.tsx
=> Production-release(v.0.0.0)

.github/workflows/discord-notify.yml
> - #12 
디스코드 알림의 가독성과 커스텀을 위해 파일을 설정하였음.
- discord-notify.yml 파일 생성
PR 생성/머지 시 뜨면 좋을 것 같은 문구 추천해 주셔도 좋슴니다.
=> Init: Discord 알림봇 설정

.env.example, package.json, pnpm-lock.yaml, src/App.tsx, src/router/routes/global-routes.tsx, src/shared/apis/config/end-point.ts, src/shared/apis/config/http.ts, src/shared/apis/config/instance.ts, src/shared/apis/domain/blind-match/queries.ts, src/shared/apis/http.ts, src/shared/apis/types/api.ts, src/shared/constants/response.ts, src/shared/utils/query-client.ts
> - #22 
- axios instance, 공통 에러메세지 상수화, 응답 타입 정의를 진행했습니다.
- axios interceptor는 요청/응답을 보내기 직전에 가로채서, 공통 처리 로직을 삽입할 수 있도록 도와줍니다.
- 서버 API 명세서의 응답 포맷을 기반으로 status, message, data 구조를 타입화하고 에러코드(400, 404 등)에 대응하는 메세지도 상수로 분리했습니다.
- http 메서드 유틸 함수도 미리 작성해 두었습니다.
- `.env.example` 파일에 BASE_URL 형식을 작성해 두었습니다.
API 통신을 효율적으로 관리하기 위해 Axios와 TanStack Query 기반의 초기 세팅을 진행했습니다.
Axios는 axiosInstance를 생성하고 공통 baseURL, Content-Type, withCredentials 설정을 적용했습니다. 
```ts
api.interceptors.response.use(
(response) => {
return response.data.data;
},
(error: AxiosError) => {
const statusCode = error.response?.status;
if (statusCode === HTTP_STATUS.UNAUTHORIZED) {
window.location.replace(routePath.LOGIN);
}
if (error.response) {
const { status, message } = error.response.data as responseTypes; …
```
=> Init: Tanstack Query / Axios 초기세팅

src/pages/home/home.tsx, src/shared/components/input/input.css.ts
> #120
- 인풋 클릭 전에 불투명 속성이 있어서 css 수정했습니다. 
- 클릭시에 흰 배경으로 변경 되도록 했습니다.
=> Fix: Input 컴포넌트 클릭 전 css 수정

src/pages/blind-match/components/entry/entry.tsx, src/pages/blind-match/components/modal/confirm-modal.tsx, src/pages/blind-match/components/use-info-form/use-info-form.tsx
> #164
인스타Id를 선택 기입할 수 있도록 수정했습니다.
- 번호, 성별, 제3자 동의만 입력해도번호팅 신청할 수 있도록 수정했습니다.
```
const isValid = Boolean(
form.phoneNumber &&
form.gender &&
agreed &&
phoneRegex.test(form.phoneNumber),
);
```
- 모달컴포넌트에서 조건을 추가해서 인스타 아이디가 없을 경우에 전화번호만 뜨도록 수정했습니다.
```
{instaId && (
<Modal.Info
label="인스타그램ID"
value={instaId}
/>
)}
```
리뷰어 혹은 팀에게 요청하고 싶은 사항이 있다면 작성해 주세요.
너무 피곤해서 머리가 안돌아가고 관리자 응모권 로직이 스파게티가아니라 동묘시장급으로 업치락뒤치락이어서 내일 꼭 완성하겠습니다,, 그전에 컨설팅 받고,,,,, 내일도 일정이있어서 저녁에 들어올게요,,, cRy 그리고 열심히 달릴게요 월요일에 api100개 연결하기 목표.
=> Fix: 번호팅 필수 조건 수정

src/pages/ticket-onboarding/constatns/onboarding-text.tsx
> - #218 
티켓 온보딩 페이지의 띄어쓰기 문제를 수정합니다.
ticket-onboarding > onboarding-text.tsx 에서 span 태그 내용을 수정합니다.
=> fix: span 내용에 띄어쓰기 추가

src/pages/ticket-onboarding/onboarding.css.ts
> - #222 
티켓 온보딩 페이지에서의 버튼 너비 문제를 수정하였습니다.
`onboarding.css.ts` 에서 position을 sticky로 수정하였습니다.
detail의 패딩 값과 마진 값을 수정하였습니다.
https://github.com/user-attachments/assets/abed8fb2-dd09-4ca0-b6d2-9256383dc08e
=> fix: position 수정 및 padding 값 수정

src/pages/show-detail/apis/queries.ts, src/shared/apis/config/interceptor.ts, src/shared/apis/types/schema.d.ts
> - #227 
공연 상세 정보 조회 API 연동 수정하였습니다.
연동 안되던 문제 수정
https://github.com/user-attachments/assets/639fcf7b-fddf-46d8-8270-4200585f96d1
=> HOTFIX: 공연 상세 조회 API 수정

src/pages/info-share/info-share.css.ts, src/pages/info-share/info-share.tsx
> - #237 
개인정보 동의 TopNavigation 추가
TovNavigation만 추가했습니다.
=> Feat: 개인정보 동의 TopNavigation 추가

src/pages/onboarding/onboarding.css.ts
> - #253 
온보딩 페이지 버튼 폰트 스타일은 변경하였습니다. (-> 프리텐다드)
=> QA-1: 온보딩 버튼 폰트 변경

src/pages/blind-match/components/modal/confirm-modal.tsx
> - #256
번호팅 모달창에서 사용자 정보 순서가 뒤바뀌있어 수정했습니다.
=> fix: 모달창 사용자 정보 순서 변경

src/pages/admin/generate-auth-key/generate-auth-key.css.ts, src/pages/admin/generate-auth-key/generate-auth-key.tsx
> - #259 
인증키 새로고침 버튼 추가 요청으로 만들었습니다
새로고침 버튼 클릭시 인증키를 다시 받아옵니다
=> Feat: 인증키 새로고침 버튼 추가

src/pages/booth-detail/components/activity-info.tsx, src/pages/booth-detail/components/booth-detail.css.ts
> - #268 
Tap바가 안 먹었던 이유는 absolute때문에 밑에 있던 ``<div>``가 Tap바를 덮고 있었어요.
absolute지우고 ``<div>``아래 ``<p>``만들어서 패딩 줘서 해결했습니다.
https://github.com/user-attachments/assets/4d0945cf-5991-4fa4-91cf-c96753631e35
=> Fix: 푸드존 체험 활동 Tap 오류

src/pages/booth-detail/components/menu-info.tsx
>  - #271
메뉴 정보가 없는 상세 정보도 있어  '메뉴가 없습니다' 추가했습니다
- '메뉴가 없습니다.' 추가했습니다.
https://github.com/user-attachments/assets/c214bab3-0f14-45bf-8cf1-5ddf8009a8bf
=> QA-2: 메뉴정보 메뉴가 없습니다 추가

src/pages/booth-detail/booth-detail.tsx, src/pages/booth/booth.tsx, src/pages/booth/components/booth-list.tsx
> - #276 
uselocation 사용해서 Chip상태 넘김
=> Fix: 부스 Chip상태 유지

src/pages/blind-match/constants/blind-match-time.ts
=> Fix: 마감 시간 및 결과 발표 시간 수정

src/pages/ticket/components/inpur-section/input-section.tsx
> - #292
이름input에는 한글만,
학번input에는 숫자4대문자1숫자1형식으로 유효성 검사를 추가했습니다.
**handleNameChange**
-  한글(자음, 모음, 완성형)을 제외한 모든 문자를 제거하는 정규 표현식(/[^ㄱ-ㅎㅏ-ㅣ가-힣]/g)을 적용했습니다.( 처음엔 가-힣만 추가하고 테스트했느데 한글은 모음부터 작성되기에 아예 작성이 안 되더라고요. 그래서 모음 자음 추가 후 테스트 해봤는데 정상적으로 작동되었습니다. 이건 알면 좋을 것 같아요! 저도 오늘 깨달았습니다!!)
**handleStudentNumChange**
- `part1`: 앞 4자리(substring(0, 4))는 숫자만 허용합니다.
- `part2`: 5번째 자리(substring(4, 5))는 영문만 허용하고, `.toUpperCase()`를 사용하여 소문자로 입력해도 자동으로 대문자로 변환합니다.
- `part3`: 6번째부터 9번째 자리(substring(5, 9))는 다시 숫자만 허용합니다.
- 이 세 부분을 `filteredValue =${part1}${part2}${part3}`를 통해 하나의 완성된 문자열로 합칩니다.
- + `if (value.length <= 4) {filteredValue = value.replace(/[^0-9]/g, '')}`이게 없으면 처음부터 영어입력이 가능해져서 추가했습니다. …
=> QA-3: 응모권 사용자 정보 입력 유효성 검사 추가

src/pages/blind-match/constants/blind-match-time.ts, src/pages/booth-detail/components/booth-detail-item/booth-detail-item.css.ts
…잘리지 않도록 개선
> - #318 
부스 상세 조회 메뉴 부분 영역을 넘지 않아도 말 줄임 표시 되었던 문제를 수정하였습니다.
=> QA-4: 부스 상세 조회 말줄임 수정

README.md, src/pages/admin/generate-auth-key/generate-auth-key.css.ts, src/pages/admin/generate-auth-key/generate-auth-key.tsx, src/pages/admin/ticket-drawing/components/drawing-main/drawing-main.tsx, src/pages/admin/ticket-drawing/components/drawing/drawing.tsx, src/pages/admin/ticket-drawing/ticket-drawing.tsx, src/pages/blind-match/components/apply-after/closed.tsx, src/pages/blind-match/constants/blind-match-time.ts, src/pages/booth-detail/components/booth-detail-item/booth-detail-item.css.ts, src/pages/ticket/components/modal-type/success-modal.tsx, src/shared/components/button/button.css.ts
=> 마지막 배포 테스트

package.json, pnpm-lock.yaml, src/app/main.tsx
> - #332 
Vercel의 analytics 설정으로 사용자 집계를 파악
Vercel의 analytics 설정으로 사용자 집계를 파악하기 위해
"@vercel/analytics": "^1.5.0" 추가하였고 main.tsx에 
`<Analytics />` 추가하였습니다.
=> Feat: Vercel 사용자 집계 추가

package.json, pnpm-lock.yaml, src/app/main.tsx
- 사용자 집계를 위해 Vercel Analytics를 추가했습니당
=> Production-release(v.1.0.0)

src/pages/booth/components/booth-list.tsx, src/pages/booth/types/types.ts
=> HotFix: 부스 조회 수정
